[build]
  base = "./"
  publish = "./dist/"
  command = "npm run build"

[template.environment]
  NAME = "shiela"
  PIC = "https://drive.google.com/file/d/1RxMZljGBNYLl0IoJIRfjEA75JXlq3g6F/view?usp=drive_link"
