[build]
  base = "./"
  publish = "./dist/"
  command = "npm run build"

[build.environment]
NAME = "shiela"
PIC = "https://raw.githubusercontent.com/deitheramurao-coder/taskperfwebsite/main/local/sample-pic.jpg"

